##
##  Makefile -- Build procedure for sample vstatus Apache module
##  Autogenerated via ``apxs -n vstatus -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
APXS=apxs2
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-DVERSION="0.0.1"
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_vstatus.o mod_vstatus.lo mod_vstatus.slo mod_vstatus.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/vstatus

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

